gomod:
  proxy: true

builds:
  # library only, so skip building
  - skip: true

release:
  github:
    owner: zerotier
    name: ztchooks

  draft: false

  prerelease: auto

  make_latest: true

  mode: append

  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

  skip_upload: true
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
